# Generated by Django 4.2.7 on 2023-12-06 03:41

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to=account.models.path_to_profile_photo
            ),
        ),
    ]
