# Generated by Django 4.2.7 on 2023-12-18 13:48

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="media/profile/pr_img.png",
                upload_to=account.models.path_to_profile_photo,
            ),
        ),
    ]
