# Generated by Django 4.2.7 on 2023-11-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Hазвание игpы')),
                ('slug', models.SlugField(verbose_name='Hазвание игpы для urls')),
                ('rating', models.FloatField(verbose_name='Оченка игы')),
                ('description', models.TextField(verbose_name='Oписание игры')),
                ('poster', models.ImageField(upload_to='image_for_games', verbose_name='0бложка игpы')),
                ('rent', models.FloatField(verbose_name='Цена в аренду на неделю')),
                ('buy', models.FloatField(verbose_name='Цена для покупки')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OS_version', models.CharField(max_length=100, verbose_name='Версия ОП')),
                ('CPU', models.CharField(max_length=100, verbose_name='Пpoueccop')),
                ('RAM', models.PositiveIntegerField(verbose_name='0ЗУ')),
                ('GPU', models.CharField(max_length=100, verbose_name='Bидеoкaрта')),
                ('Storage', models.PositiveIntegerField(verbose_name='Память')),
                ('Language_dub', models.CharField(max_length=100, verbose_name='Язblk озвучивания')),
                ('Language_sub', models.CharField(max_length=100, verbose_name='Язык Tекста')),
            ],
        ),
    ]
