# Generated by Django 4.2.7 on 2023-12-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "OS_version",
                    models.CharField(max_length=100, verbose_name="Версия ОП"),
                ),
                ("CPU", models.CharField(max_length=100, verbose_name="Пpoцeccop")),
                ("RAM", models.PositiveIntegerField(verbose_name="0ЗУ")),
                ("GPU", models.CharField(max_length=100, verbose_name="Bидеoкaрта")),
                ("Storage", models.PositiveIntegerField(verbose_name="Память")),
                (
                    "Language_dub",
                    models.CharField(max_length=100, verbose_name="Язык озвучивания"),
                ),
                (
                    "Language_sub",
                    models.CharField(max_length=100, verbose_name="Язык текста"),
                ),
            ],
            options={
                "verbose_name": "SystemRequirement",
                "verbose_name_plural": "SystemRequirements",
            },
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Game title")),
                ("slug", models.SlugField(max_length=250, verbose_name="Slug field")),
                (
                    "rating",
                    models.FloatField(
                        validators=[main_app.models.validate_float_range],
                        verbose_name="Game rating",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Game description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=main_app.models.poster_upload_path,
                        verbose_name="Game poster",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="categories", to="main_app.category"
                    ),
                ),
                (
                    "systemreq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_req",
                        to="main_app.systemrequirements",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.games"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="main_app_ca_name_41b8fc_idx"),
        ),
        migrations.AddIndex(
            model_name="games",
            index=models.Index(fields=["id", "slug"], name="main_app_ga_id_0b5428_idx"),
        ),
        migrations.AddIndex(
            model_name="games",
            index=models.Index(fields=["name"], name="main_app_ga_name_c7408d_idx"),
        ),
        migrations.AddIndex(
            model_name="games",
            index=models.Index(
                fields=["-created"], name="main_app_ga_created_c5052d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="main_app_co_created_69df10_idx"
            ),
        ),
    ]
