# Generated by Django 4.2.7 on 2023-11-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
