# Generated by Django 4.2.7 on 2023-11-29 15:13

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_games_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="rating",
            field=models.FloatField(
                validators=[main_app.models.validate_float_range],
                verbose_name="Game rating",
            ),
        ),
    ]
