# Generated by Django 4.2.7 on 2023-11-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_systemrequirements_cpu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='systemrequirements',
            options={'verbose_name': 'SystemRequirement', 'verbose_name_plural': 'SystemRequirements'},
        ),
        migrations.AddField(
            model_name='games',
            name='systemreq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.systemrequirements'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='rating',
            field=models.FloatField(verbose_name='Оценка игры'),
        ),
    ]
