# Generated by Django 4.2.7 on 2023-11-22 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_app",
            "0003_alter_games_options_alter_systemrequirements_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="games",
            options={
                "ordering": ["-added"],
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
            },
        ),
        migrations.AddField(
            model_name="games",
            name="added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
