# Generated by Django 4.2.7 on 2023-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_alter_games_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games",
            name="category",
        ),
        migrations.AddField(
            model_name="games",
            name="categories",
            field=models.ManyToManyField(related_name="games", to="main_app.category"),
        ),
    ]
