# Generated by Django 4.2.7 on 2023-12-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_remove_games_category_games_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories", to="main_app.category"
            ),
        ),
    ]
