# Generated by Django 4.2.7 on 2023-11-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_alter_games_buy_alter_games_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="poster",
            field=models.ImageField(
                upload_to="Games_images/<django.db.models.fields.CharField>",
                verbose_name="Game poster",
            ),
        ),
    ]
