# Generated by Django 4.2.7 on 2023-11-23 06:45

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0006_alter_games_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="poster",
            field=models.ImageField(
                upload_to=main_app.models.poster_upload_path, verbose_name="Game poster"
            ),
        ),
    ]
