# Generated by Django 4.2.7 on 2023-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_remove_feature_person_feature_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="company",
        ),
        migrations.AddField(
            model_name="feature",
            name="company",
            field=models.ManyToManyField(related_name="company", to="about.company"),
        ),
    ]
