# Generated by Django 4.2.7 on 2023-12-10 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("period", models.IntegerField(default=7)),
                ("discount", models.FloatField(default=0.05)),
                ("active", models.BooleanField(default=True)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="main_app.games",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Key",
                "verbose_name_plural": "Keys",
            },
        ),
    ]
